

# Name of your site (displayed in the header)
name: Jer Noble

# Short bio or description (displayed in the header)
description: Just a guy with a web site

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  github: jernoble/jekyll_test
  twitter: jernoble

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://jernoble.github.io/jekyll_test/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/jekyll_test"

theme: jekyll-theme-minimal
